# Generated by Django 4.0.4 on 2023-01-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAnswer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Відповідь'),
        ),
    ]
