# Generated by Django 4.0.4 on 2023-01-02 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ScientificMaterials', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва курсу')),
                ('course_slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет')),
                ('date_creating', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id коментаря')),
                ('comment_text', models.TextField(verbose_name='Текст коментаря')),
                ('add_comment_date', models.DateField(auto_now_add=True, verbose_name='Дата відправлення')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseconfig')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Відправник')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testsconfig')),
            ],
            options={
                'ordering': ['add_comment_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Дата призначення')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseconfig')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testsconfig')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='AssignedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_material_date', models.DateField(auto_now_add=True, verbose_name='Дата призначення')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseconfig')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScientificMaterials.scientificmaterials')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testsconfig')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
