# Generated by Django 4.0.4 on 2022-12-29 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='add_comment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата відправлення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Відправник'),
        ),
    ]
