# Generated by Django 4.0.4 on 2022-12-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_comment_add_comment_date_alter_comment_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['add_comment_date']},
        ),
    ]
