# Generated by Django 4.0.4 on 2022-12-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScientificMaterials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientificmaterials',
            options={'ordering': ['pk']},
        ),
    ]
