# Generated by Django 4.0.4 on 2022-11-15 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.CharField(max_length=255, verbose_name='Назва тесту')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('theme_test', models.CharField(max_length=255, verbose_name='Опис тесту ')),
                ('max_test_result', models.FloatField(verbose_name='Максимальний бал тесту')),
                ('date_creating', models.DateField(auto_now_add=True)),
                ('author_of_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор тесту')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TestsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=255, verbose_name='Назва функції')),
                ('question', models.TextField(verbose_name='Завдання')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testsconfig')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='DataForTestingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_test_data', models.CharField(max_length=255, verbose_name='Вхідні аргументи')),
                ('input_test_data_type', models.CharField(max_length=255, verbose_name='Тип вхідних данних')),
                ('output_test_data', models.CharField(max_length=255, verbose_name='Вихідні данні')),
                ('output_test_data_type', models.CharField(max_length=255, verbose_name='Тип вихідних данних')),
                ('num_of_point', models.FloatField(verbose_name='Кількість балів за вдалу перевірку')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testssection')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
