# Generated by Django 4.0.4 on 2022-12-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsconfig',
            name='create_func_template',
            field=models.BooleanField(default=True, verbose_name='Автоматичне створення шаблону функції'),
        ),
    ]
