# Generated by Django 4.0.4 on 2022-12-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_testsconfig_create_func_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsconfig',
            name='autocomplete',
            field=models.BooleanField(default=True, verbose_name='Дозвіл на автозавершення'),
        ),
    ]
