# Generated by Django 4.0.4 on 2023-01-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testsconfig_autocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsconfig',
            name='pre_end_check',
            field=models.BooleanField(default=True, verbose_name='Дозвіл на перевірку, перед завершеням тесту'),
        ),
    ]
